---
title: "CreatingRFunctions"
author: "Natasha Griffin"
date: "10/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Example without using functions
```{r}

airtemps <- c(212, 30.3, 78, 32)
celsius1 <- (airtemps[1]-32)*5/9
celsius2 <- (airtemps[2]-32)*5/9
celsius3 <- (airtemps[3]-32)*5/9

```

## Create a function to do the same thing
```{r}

fahr_to_celsius <- function(fahr) {
  celsius <- (fahr-32)*5/9
  return(celsius)
}

```

## Test function
```{r}

celsius4 <- fahr_to_celsius(airtemps[1])
celsius1 == celsius4

celsius <- fahr_to_celsius(airtemps)
celsius

```

## Challenge: write and test celsius to fahrenheit function
```{r}
#' Converts Celsius to Fahrenheit
#'
#' This function takes in temperature data in degrees Celsius to be converted to degrees Fahrenheit
#' @param celsius Temperature value or vector in degrees Celsius
#' @return Temperature value in degrees Celsius
celsius_to_fahr <- function(celsius) {
  fahr <- (celsius*9/5 +32)
  return(fahr)
}

fahr <- celsius_to_fahr(celsius)
fahr

fahr == airtemps

```



